version: "3.8"

services:
  now-playing:
    image: irrelativity/now-playing:latest
    container_name: now-playing
    ports:
      - "0.0.0.0:3003:3003"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - NEXT_PUBLIC_FETCH_TIMEOUT=${FETCH_TIMEOUT:-8000}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - USERNAME_MAP=${USERNAME_MAP}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
