version: "3.8"

services:
  plex-api-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FETCH_TIMEOUT=${FETCH_TIMEOUT:-8000}
    container_name: plex-api-dashboard
    ports:
      - "0.0.0.0:3003:3003"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - FETCH_TIMEOUT=${FETCH_TIMEOUT:-8000}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
