name: Deploy Plex API Dashboard

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        shell: powershell
        env:
          NEXT_PUBLIC_PLEX_URL: ${{ secrets.NEXT_PUBLIC_PLEX_URL }}
          NEXT_PUBLIC_PLEX_TOKEN: ${{ secrets.NEXT_PUBLIC_PLEX_TOKEN }}
          NEXT_PUBLIC_FETCH_TIMEOUT: ${{ secrets.NEXT_PUBLIC_FETCH_TIMEOUT }}
        run: |
          docker-compose build --build-arg NEXT_PUBLIC_PLEX_URL="$env:NEXT_PUBLIC_PLEX_URL" --build-arg NEXT_PUBLIC_PLEX_TOKEN="$env:NEXT_PUBLIC_PLEX_TOKEN" --build-arg NEXT_PUBLIC_FETCH_TIMEOUT="$env:NEXT_PUBLIC_FETCH_TIMEOUT" plex-dashboard

      - name: Deploy service
        shell: powershell
        env:
          NODE_ENV: production
          NEXT_PUBLIC_PLEX_URL: ${{ secrets.NEXT_PUBLIC_PLEX_URL }}
          NEXT_PUBLIC_PLEX_TOKEN: ${{ secrets.NEXT_PUBLIC_PLEX_TOKEN }}
          NEXT_PUBLIC_FETCH_TIMEOUT: ${{ secrets.NEXT_PUBLIC_FETCH_TIMEOUT }}
        run: |
          @"
          NODE_ENV=production
          NEXT_PUBLIC_PLEX_URL=$env:NEXT_PUBLIC_PLEX_URL
          NEXT_PUBLIC_PLEX_TOKEN=$env:NEXT_PUBLIC_PLEX_TOKEN
          NEXT_PUBLIC_FETCH_TIMEOUT=$env:NEXT_PUBLIC_FETCH_TIMEOUT
          "@ | Out-File -Encoding utf8 .env

          $containerExists = docker ps -a --filter "name=plex-dashboard" --format "{{.Names}}"
          if ($containerExists) {
            Write-Host "Stopping and removing existing container..."
            docker stop plex-dashboard
            docker rm plex-dashboard
          }

          docker-compose up -d plex-dashboard

          docker ps -f name=plex-dashboard

      - name: Cleanup
        shell: powershell
        run: |
          docker image prune -a --filter "until=72h" --force
