name: Deploy Plex Dashboard

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        shell: powershell
        env:
          FETCH_TIMEOUT: ${{ secrets.FETCH_TIMEOUT }}
        run: |
          $env:NEXT_PUBLIC_FETCH_TIMEOUT = "${{ secrets.FETCH_TIMEOUT }}"

          docker-compose build

      - name: Deploy service
        shell: powershell
        env:
          NODE_ENV: production
          PLEX_URL: ${{ secrets.PLEX_URL }}
          PLEX_TOKEN: ${{ secrets.PLEX_TOKEN }}
          FETCH_TIMEOUT: ${{ secrets.FETCH_TIMEOUT }}
        run: |
          @"
          NODE_ENV=production
          PLEX_URL=${{ secrets.PLEX_URL }}
          PLEX_TOKEN=${{ secrets.PLEX_TOKEN }}
          FETCH_TIMEOUT=${{ secrets.FETCH_TIMEOUT }}
          "@ | Out-File -Encoding utf8 .env

          $containerExists = docker ps -a --filter "name=plex-api-dashboard" --format "{{.Names}}"
          if ($containerExists) {
            Write-Host "Stopping and removing existing container..."
            docker stop plex-api-dashboard
            docker rm plex-api-dashboard
          }

          docker-compose up -d

          docker ps -f name=plex-api-dashboard

      - name: Cleanup
        shell: powershell
        run: |
          docker image prune -a --filter "until=72h" --force
